server:
  port: 8899

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379

